/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PersonLinkedin {
    /**
     * The last section of the person's LinkedIn profile URL (e.g. in/alex-maccaw-ab592978).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("handle")
    public String handle;
    public PersonLinkedin withHandle(String handle) {
        this.handle = handle;
        return this;
    }
    
}
