/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PersonGravatarUrls {
    /**
     * The title of the website listed by the person on their Gravatar profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public String title;
    public PersonGravatarUrls withTitle(String title) {
        this.title = title;
        return this;
    }
    
    /**
     * The website URL listed by the person on their Gravatar profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public String value;
    public PersonGravatarUrls withValue(String value) {
        this.value = value;
        return this;
    }
    
}
