/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PersonGithub {
    /**
     * The profile picture of the person's GitHub profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("avatar")
    public String avatar;
    public PersonGithub withAvatar(String avatar) {
        this.avatar = avatar;
        return this;
    }
    
    /**
     * The person's website as listed on their GitHub profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("blog")
    public String blog;
    public PersonGithub withBlog(String blog) {
        this.blog = blog;
        return this;
    }
    
    /**
     * The company the person works for as listed on their GitHub profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company")
    public String company;
    public PersonGithub withCompany(String company) {
        this.company = company;
        return this;
    }
    
    /**
     * The number of followers the person has on GitHub.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("followers")
    public Long followers;
    public PersonGithub withFollowers(Long followers) {
        this.followers = followers;
        return this;
    }
    
    /**
     * The number of people the person follows on GitHub.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("following")
    public Long following;
    public PersonGithub withFollowing(Long following) {
        this.following = following;
        return this;
    }
    
    /**
     * The person's GitHub profile username (e.g. maccman).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("handle")
    public String handle;
    public PersonGithub withHandle(String handle) {
        this.handle = handle;
        return this;
    }
    
    /**
     * The ID of the person's GitHub profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Long id;
    public PersonGithub withId(Long id) {
        this.id = id;
        return this;
    }
    
}
