/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PersonGravatar {
    /**
     * The profile picture of the person's Gravatar profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("avatar")
    public String avatar;
    public PersonGravatar withAvatar(String avatar) {
        this.avatar = avatar;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("avatars")
    public PersonGravatarAvatars[] avatars;
    public PersonGravatar withAvatars(PersonGravatarAvatars[] avatars) {
        this.avatars = avatars;
        return this;
    }
    
    /**
     * The person's Gravatar profile username (e.g., maccman).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("handle")
    public String handle;
    public PersonGravatar withHandle(String handle) {
        this.handle = handle;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("urls")
    public PersonGravatarUrls[] urls;
    public PersonGravatar withUrls(PersonGravatarUrls[] urls) {
        this.urls = urls;
        return this;
    }
    
}
