/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PersonGeo {
    /**
     * The city the person lives in based on their location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("city")
    public String city;
    public PersonGeo withCity(String city) {
        this.city = city;
        return this;
    }
    
    /**
     * The country the person lives in based on their location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    public String country;
    public PersonGeo withCountry(String country) {
        this.country = country;
        return this;
    }
    
    /**
     * The country code of the country the person lives in based on their location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("countryCode")
    public String countryCode;
    public PersonGeo withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    /**
     * The latitude based on the person's location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lat")
    public Float lat;
    public PersonGeo withLat(Float lat) {
        this.lat = lat;
        return this;
    }
    
    /**
     * The longitude based on the person's location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lng")
    public Float lng;
    public PersonGeo withLng(Float lng) {
        this.lng = lng;
        return this;
    }
    
    /**
     * The state the person lives in based on their location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("state")
    public String state;
    public PersonGeo withState(String state) {
        this.state = state;
        return this;
    }
    
    /**
     * The state code of the state the person lives in based on their location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stateCode")
    public String stateCode;
    public PersonGeo withStateCode(String stateCode) {
        this.stateCode = stateCode;
        return this;
    }
    
}
