/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PersonTwitter {
    /**
     * The profile picture of the person's Twitter profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("avatar")
    public String avatar;
    public PersonTwitter withAvatar(String avatar) {
        this.avatar = avatar;
        return this;
    }
    
    /**
     * The person's bio as listed on their Twitter profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bio")
    public String bio;
    public PersonTwitter withBio(String bio) {
        this.bio = bio;
        return this;
    }
    
    /**
     * The number of tweets the person has liked on Twitter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("favorites")
    public Long favorites;
    public PersonTwitter withFavorites(Long favorites) {
        this.favorites = favorites;
        return this;
    }
    
    /**
     * The number of followers the person has on Twitter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("followers")
    public Long followers;
    public PersonTwitter withFollowers(Long followers) {
        this.followers = followers;
        return this;
    }
    
    /**
     * The number of people the person follows on Twitter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("following")
    public Long following;
    public PersonTwitter withFollowing(Long following) {
        this.following = following;
        return this;
    }
    
    /**
     * The person's Twitter profile username (e.g. maccaw).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("handle")
    public String handle;
    public PersonTwitter withHandle(String handle) {
        this.handle = handle;
        return this;
    }
    
    /**
     * The ID of the person's Twitter profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Long id;
    public PersonTwitter withId(Long id) {
        this.id = id;
        return this;
    }
    
    /**
     * The person's location as listed on their Twitter profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("location")
    public String location;
    public PersonTwitter withLocation(String location) {
        this.location = location;
        return this;
    }
    
    /**
     * The person's website as listed on their Twitter profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("site")
    public String site;
    public PersonTwitter withSite(String site) {
        this.site = site;
        return this;
    }
    
    /**
     * The number of tweets the person has shared on Twitter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("statuses")
    public Long statuses;
    public PersonTwitter withStatuses(Long statuses) {
        this.statuses = statuses;
        return this;
    }
    
}
