/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.utils;

import java.net.http.HttpRequest.BodyPublisher;

public class SerializedBody {
    public String contentType;
    public BodyPublisher body;
}
