/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package clearbit_dev.person_v2.models.operations;

import clearbit_dev.person_v2.utils.SpeakeasyMetadata;

public class FindRequest {
    /**
     * The name of the company the person works for
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=company")
    public String company;
    public FindRequest withCompany(String company) {
        this.company = company;
        return this;
    }
    
    /**
     * The domain of the company the person works for
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=company_domain")
    public String companyDomain;
    public FindRequest withCompanyDomain(String companyDomain) {
        this.companyDomain = companyDomain;
        return this;
    }
    
    /**
     * The email address to look up
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=email")
    public String email;
    public FindRequest withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * The person's Facebook profile URL
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=facebook")
    public String facebook;
    public FindRequest withFacebook(String facebook) {
        this.facebook = facebook;
        return this;
    }
    
    /**
     * The person's last name. If you have this, passing this is strongly recommended to improve match rates
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=family_name")
    public String familyName;
    public FindRequest withFamilyName(String familyName) {
        this.familyName = familyName;
        return this;
    }
    
    /**
     * The person's first name
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=given_name")
    public String givenName;
    public FindRequest withGivenName(String givenName) {
        this.givenName = givenName;
        return this;
    }
    
    /**
     * The person's IP address. If you have this, passing this is strongly recommended to improve match rates
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ip_address")
    public String ipAddress;
    public FindRequest withIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }
    
    /**
     * The person's LinkedIn profile URL
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=linkedin")
    public String linkedin;
    public FindRequest withLinkedin(String linkedin) {
        this.linkedin = linkedin;
        return this;
    }
    
    /**
     * The city or country where the person lives
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=location")
    public String location;
    public FindRequest withLocation(String location) {
        this.location = location;
        return this;
    }
    
    /**
     * The person's Twitter profile username
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=twitter")
    public String twitter;
    public FindRequest withTwitter(String twitter) {
        this.twitter = twitter;
        return this;
    }
    
    /**
     * A webhook URL that results will be sent to
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=webhook_url")
    public String webhookUrl;
    public FindRequest withWebhookUrl(String webhookUrl) {
        this.webhookUrl = webhookUrl;
        return this;
    }
    
}
